#!/bin/bash

benchmark-ssh-ciphers() {
    for cipher in $(ssh -Q cipher); do
        dd if=/dev/zero bs=1000000 count=1000 2> /dev/null | ssh -c ${cipher} localhost "(time -p cat) > /dev/null" 2>&1 | grep real | awk -v cipher=${cipher} '{printf cipher": "(1000 / $2)" MB/s\n" }';
    done
}

setup-temp-authorized-keys() {
    test -f ~/.ssh/authorized_keys && {
        mv ~/.ssh/authorized_keys ~/.ssh/authorized_keys.backup || {
	    echo "Moving ~/.ssh/authorized_keys to ~/.ssh/authorized_keys.backup failed, aborting test."
	        exit 1;
	    }
	}
    cat ~/.ssh/*.pub > ~/.ssh/authorized_keys;
    chmod 400 ~/.ssh/authorized_keys;
}

restore-orig-authorized-keys() {
    test -f ~/.ssh/authorized_keys.backup && {
		rm -f ~/.ssh/authorized_keys;
        mv ~/.ssh/authorized_keys.backup ~/.ssh/authorized_keys;
    }
}

exec-benchmark() {
    setup-temp-authorized-keys;
	benchmark-ssh-ciphers;
	restore-orig-authorized-keys;
}

if [[ $(uname -s) == "Darwin" ]]; then
	if [[ $(sudo systemsetup -getremotelogin) =~ "Off" ]]; then
        sudo systemsetup -setremotelogin on;
		echo "$(date +%s)" > ~/.ssh/remotelogin-enabled;
	fi
fi

exec-benchmark;

if [[ $(uname -s) == "Darwin" ]]; then
	test -f ~/.ssh/remotelogin-enabled && {
        sudo systemsetup -setremotelogin off && {
		    rm ~/.ssh/remotelogin-enabled;
	    }
    }
fi
